import { expect, test } from 'vitest';
import { Universe } from './types';
import { getExpandedUniverse } from './getExpandedUniverse';

function parseUniverse(value: string): Universe {
  return value
    .split('\n')
    .filter(Boolean)
    .map((line) => line.trim().split(''));
}

const input = `
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
`;

const expected = `
 ....#........
 .........#...
 #............
 .............
 .............
 ........#....
 .#...........
 ............#
 .............
 .............
 .........#...
 #....#.......
`;

test('galaxy is expanded as expected', () => {
  const universe = parseUniverse(input);
  const expectedUniverse = parseUniverse(expected);

  const result = getExpandedUniverse(universe);

  expect(JSON.stringify(result)).toEqual(JSON.stringify(expectedUniverse));
});
